CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "phone" varchar not null, "email" varchar, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "users_phone_unique" on "users" ("phone");
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("phone" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("phone"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "product_heads" ("id" integer primary key autoincrement not null, "aligen" varchar, "key" varchar, "sortable" tinyint(1) default '0', "title" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "stocks" ("id" integer primary key autoincrement not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "products" ("pcode" varchar not null, "name" varchar not null, "image" varchar, "type" varchar not null, "unit" varchar, "brand" varchar, "ccode" varchar, "created_at" datetime, "updated_at" datetime, primary key ("pcode"));
CREATE TABLE IF NOT EXISTS "categories" ("id" integer primary key autoincrement not null, "name" varchar not null, "code" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "categories_code_unique" on "categories" ("code");
INSERT INTO migrations VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(4,'2024_03_15_031826_create_product_heads_table',1);
INSERT INTO migrations VALUES(5,'2024_03_15_074807_create_stocks_table',1);
INSERT INTO migrations VALUES(6,'2024_03_15_081519_create_products_table',1);
INSERT INTO migrations VALUES(7,'2024_03_15_105126_create_categories_table',2);
